FROM arm64v8/alpine:3.7
LABEL image=ficoos/znc:arm64v8
ENV ARCH arm64v8
MAINTAINER Saggi Mizrahi "saggi@mizrahi.cc"

RUN apk update && \
    apk add znc

RUN adduser znc znc
ADD docker-entrypoint.sh /entrypoint.sh
ADD znc.conf.default /znc.conf.default
RUN chmod 644 /znc.conf.default

VOLUME /znc-data

EXPOSE 6667
ENTRYPOINT ["/entrypoint.sh"]
CMD [""]
